services:
  db:
    image: postgres:16-alpine
    container_name: dahabshiil-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dahabshiil_bank
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dahabshiil_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
